name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        rust: ['1.90', '1.91']
        type: ['', '--release']
        target: ['wasm32-wasip1', 'wasm32-wasip1-threads', 'wasm32-wasip2']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - run: rustup default ${{ matrix.rust }}
    - run: rustup target add ${{ matrix.target }}
    - name: Run tests
      run: cargo test --target ${{ matrix.target }} ${{ matrix.type }}
      continue-on-error: true
