name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        rust: [
          '1.90',
          '1.91'
        ]
        runner: ['', '.wasmer']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup default ${{ matrix.rust }}
    - uses: bytecodealliance/actions/wasmtime/setup@v1
    - uses: wasmerio/setup-wasmer@v1
    - run: rustup target add wasm32-wasip1-threads
    - run: cargo test --config .cargo/comfig${{ matrix.runner }}.toml --target wasm32-wasip1-threads --release
